dogAdoption/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using dogAdoption.Models;
using System.Collections.Generic;

namespace dogAdoption.Controllers;

public class AdminController : Controller
{
    public IActionResult MainAdmin()
    {
        return View();
    }
}

dogAdoption/Controllers/DogsAdminController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using dogAdoption.Models;
using dogAdoption.Data;
using System.Threading.Tasks;

namespace dogAdoption.Controllers;

public class DogsAdminController : Controller
{
    
    private readonly AppDbContext _databaseContext;
    public DogsAdminController(AppDbContext databaseContext)
    {
        _databaseContext = databaseContext;
    }

    public IActionResult adminDog()
    {
        IEnumerable<Dog> dogs =  _databaseContext.dogs.ToList();
        return View(dogs);
    }


    [HttpGet]
    public IActionResult createDog()
    {
        return View();
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> createDog(Dog dataInput)
    {
        if(ModelState.IsValid)
        {
            List<Dog> allDogs = await _databaseContext.dogs.ToListAsync();
            foreach(var dog in allDogs)
            {
                if(dog.Name == dataInput.Name)
                {
                    return BadRequest("Dog with same name exists in the database");
                }
            }
            var checkingIfDogExists = await _databaseContext.dogs.FindAsync(dataInput.Id);
            if(checkingIfDogExists == null)
            {

                _databaseContext.dogs.Add(dataInput);
                await _databaseContext.SaveChangesAsync();
                return RedirectToAction(nameof(adminDog));
            }
            return View(nameof(createDog));
        }
        return View(nameof(createDog));
    }


    public async Task<IActionResult> viewDog(int id)
    {
        if(id == 0 ) { return NotFound(); }
        var findDog = await _databaseContext.dogs.FindAsync(id);
        if (findDog == null)
        {
            return NotFound();
        }
        return View(findDog);
    }


    [HttpPost]
    public async Task<IActionResult> deleteDog(int? id)
    {
        if (id == 0 && id == null)
        {
            return BadRequest();
        }
        var findDog = await _databaseContext.dogs.FindAsync(id);
        if (findDog == null)
        {
            return NotFound();
        }
        _databaseContext.dogs.Remove(findDog);
        await _databaseContext.SaveChangesAsync();
        return RedirectToAction(nameof(adminDog));
    }


    [HttpGet]
    public async Task<IActionResult> updateDog(int id)
    {
        var dog = await _databaseContext.dogs.FindAsync(id);
        if(dog == null)
        {
            return BadRequest();
        }
        return View(dog);
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> updateDog(Dog dogInput)
    {
        _databaseContext.Entry(dogInput).State = EntityState.Modified;
        await _databaseContext.SaveChangesAsync();
        return RedirectToAction(nameof(adminDog));

    }


    public ActionResult adoptedDogs()
    {
        var dogs = _databaseContext.dogs.ToList();
        IEnumerable<Dog> adoptedDogs = from  dog in dogs
                        where dog.adopted == true
                        select dog;
        return View(adoptedDogs);
    }

}

dogAdoption/Views/DogsAdmin/adminDog.cshtml
  @model IEnumerable<dogAdoption.Models.Dog>;
  
  <div class="">
        <div class="container mx-auto max-w-6xl px-10 py-20">
            <h1 class="aboutheader pb-6">
                <a asp-action="MainAdmin" asp-controller="Admin">Main-Admin </a>
            </h1>
            <div class="pb-5">
                <h1 class="font-sans my-5 text-4xl bg-red-500 py-4 px-10">Dogs-Menu</h1>
            </div>
            <div class="pb-10">
                <button class="font-sans text-xl bg-black py-3 px-10 text-white">
                    <a asp-action="createDog" asp-controller="DogsAdmin">Add-Dog</a>
                </button>
                <button class="font-sans text-xl bg-black py-3 px-10 text-white">
                     <a asp-action="adoptedDogs" asp-controller="DogsAdmin">AdoptedDogs-lists</a>
                </button>
            </div>


            <div class="pb-8">
                <h1 class="font-sans text-2xl pb-2">@Model.Count() Dogs in the database</h1>
                <h1 class="font-sans text-2xl">@Model.Where(a => a.adopted==true).Count() Dogs adopted</h1>
            </div>


            @if (Model.Count() >= 1)
            {
                <h1 class="detailsheader pb-6">List of Dogs</h1>
                <table class="table tablefont table-fixed w-full text-center ">
                    <thead class="bg-black text-white">
                        <tr>
                            <th class="py-2">Id</th>
                            <th>Name</th>
                            <th>Color</th>
                            <th>Disability</th>
                            <th>Sex</th>
                            <th>Option1</th>
                            <th>Option2</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr class="border-b-2 text-xl font-serif text-gray-700 border-red-600">
                            <td class="py-4 ">@item.Id</td>
                            <th class="underline"><a asp-action="viewDog" asp-route-id="@item.Id"  asp-controller="DogsAdmin">@item.Name</a></th>
                            <th>@item.Color</th>
                            <th>@item.Disability</th>
                            <th>@item.Color</th>
                            <th><button class="bg-green-700 text-white text-xl py-2 px-4"> <a asp-action="updateDog"  asp-route-id="@item.Id" asp-controller="DogsAdmin">Update-Dog</a></button></th>
                            <th><button class="bg-red-700 text-white text-xl py-2 px-4"> <a asp-action="deleteDog" asp-route-id="@item.Id" asp-controller="DogsAdmin">Delete-Dog</a></button></th>
                        </tr>
                        }
                    </tbody>
                </table>

            } else {
                <h1 class="font-sans text-4xl tex-red-600 align-center py-20">Please add a Dog, the database is null</h1>
            }

        </div>
    </div>

dogAdoption/Views/DogsAdmin/createDog.cshtml
@model dogAdoption.Models.Dog;

<div class="">
        <div class="container mx-auto max-w-3xl px-10 py-20">
            <h1 class="detailsheader"> Add-a-Dog</h1>
            <form method="post">
                <div asp-validation-summary="All" class="text-red-700"></div>
                <div class="py-2 flex flex-col">
                    <label asp-for="Name" class="font-serif text-xl"></label>
                    <input asp-for="Name" type="text" class="w-full py-2 px-4 border-2 border-black">
                    <span asp-validation-for="Name" class="text-red-700"></span>
                </div>
                <div class="py-2 flex flex-col">
                    <label asp-for="Age" class="font-serif text-xl"></label>
                    <input asp-for="Age" type="number" class="w-full py-2 px-4 border-2 border-black">
                    <span asp-validation-for="Age" class="text-red-700"></span>
                </div>
                <div class="py-2 flex flex-col">
                    <label asp-for="Color" class="font-serif text-xl"></label>
                    <input asp-for="Color" type="text" class="w-full py-2 px-4 border-2 border-black">
                    <span asp-validation-for="Color" class="text-red-700"></span>
                </div>
                <div class="py-2 flex flex-col">
                    <label asp-for="HealthCondition" class="font-serif text-xl"></label>
                    <input type="text" asp-for="HealthCondition" class="w-full py-2 px-4 border-2 border-black">
                    <span asp-validation-for="HealthCondition"></span>
                </div>
                <div class="py-2 flex flex-col">
                    <label asp-for="EyesColor" class="font-serif text-xl"></label>
                    <input asp-for="EyesColor" type="text" class="w-full py-2 px-4 border-2 border-black">
                </div>
                <div class="py-2 flex flex-col">
                    <label asp-for="Disability" class="font-serif text-xl"></label>
                    <input type="text" asp-for="Disability" class="w-full py-2 px-4 border-2 border-black">
                   <span asp-asp-validation-for="Disability"></span>
                </div>
                <div class="py-2 flex flex-col">
                    <label asp-for="TrainedLevel" class="font-serif text-xl"></label>
                    <input type="text" asp-for="TrainedLevel" class="w-full py-2 px-4 border-2 border-black">
                    <span asp-validation-for="TrainedLevel"></span>
                </div>
                <button type="submit" class="font-sans text-xl bg-red-600 py-3 w-full text-white">Submit Create</button>
            </form>
        </div>
    </div>

@section Scripts{
    @{ <partial name="_ValidationScriptsPartial" /> }
}

dogAdoption/Views/DogsAdmin/updateDog.cshtml
@model dogAdoption.Models.Dog;

<div class="">
        <div class="container mx-auto max-w-3xl px-10 py-20">
            <h1 class="detailsheader">Update-Dog</h1>
            <form method="post" >
                <div asp-validation-summary="All" class="text-red-700"></div>
                <div class="py-2 flex flex-col">
                    <label asp-for="Name" class="font-serif text-xl"></label>
                    <input asp-for="Name" type="text" class="w-full py-2 px-4 border-2 border-black">
                    <span asp-validation-for="Name" class="text-red-700"></span>
                </div>
                <div class="py-2 flex flex-col">
                    <label asp-for="Age" class="font-serif text-xl"></label>
                    <input asp-for="Age" type="number" class="w-full py-2 px-4 border-2 border-black">
                    <span asp-validation-for="Age" class="text-red-700"></span>
                </div>
                <div class="py-2 flex flex-col">
                    <label asp-for="Color" class="font-serif text-xl"></label>
                    <input asp-for="Color" type="text" class="w-full py-2 px-4 border-2 border-black">
                    <span asp-validation-for="Color" class="text-red-700"></span>
                </div>
                <div class="py-2 flex flex-col">
                    <label asp-for="HealthCondition" class="font-serif text-xl"></label>
                    <input type="text" asp-for="HealthCondition" class="w-full py-2 px-4 border-2 border-black">
                    <span asp-validation-for="HealthCondition"></span>
                </div>
                <div class="py-2 flex flex-col">
                    <label asp-for="EyesColor" class="font-serif text-xl"></label>
                    <input asp-for="EyesColor" type="text" class="w-full py-2 px-4 border-2 border-black">
                </div>
                <div class="py-2 flex flex-col">
                    <label asp-for="Disability" class="font-serif text-xl"></label>
                    <input type="text" asp-for="Disability" class="w-full py-2 px-4 border-2 border-black">
                   <span asp-asp-validation-for="Disability"></span>
                </div>
                <div class="py-2 flex flex-col">
                    <label asp-for="TrainedLevel" class="font-serif text-xl"></label>
                    <input type="text" asp-for="TrainedLevel" class="w-full py-2 px-4 border-2 border-black">
                    <span asp-validation-for="TrainedLevel"></span>
                </div>
                <button type="submit" class="font-sans text-xl bg-red-600 py-3 w-full text-white">Update Dog</button>
            </form>
        </div>
    </div>

@section Scripts{
    @{ <partial name="_ValidationScriptsPartial" /> }
}

dogAdoption/Views/DogsAdmin/viewDog.cshtml
@model dogAdoption.Models.Dog;

<div class="">
        <div class="container mx-auto max-w-3xl px-10 py-20">
            <h1 class="detailsheader">@Model.Name Dog-Details</h1>

            @* return to dashboard button *@
            <form>
                <div class="py-2 flex flex-col">
                    <label for="" class="font-serif text-xl">Name</label>
                    <div  class="w-full py-2 px-4 border-2 border-black">@Model.Name</div>
                </div>
                <div class="py-2 flex flex-col">
                    <label for="" class="font-serif text-xl">Age</label>
                     <div  class="w-full py-2 px-4 border-2 border-black">@Model.Age</div>
                </div>
                <div class="py-2 flex flex-col">
                    <label for="" class="font-serif text-xl">Color</label>
                     <div  class="w-full py-2 px-4 border-2 border-black">@Model.Color</div>
                </div>
                <div class="py-2 flex flex-col">
                    <label for="" class="font-serif text-xl">Eyes-color</label>
                     <div  class="w-full py-2 px-4 border-2 border-black">@Model.EyesColor</div>
                </div>
                <div class="py-2 flex flex-col">
                    <label for="" class="font-serif text-xl">HealthCondition</label>
                     <div  class="w-full py-2 px-4 border-2 border-black">@Model.HealthCondition</div>
                </div>
                <div class="py-2 flex flex-col">
                    <label for="" class="font-serif text-xl">Disability</label>
                     <div  class="w-full py-2 px-4 border-2 border-black">@Model.Disability</div>
                </div>
                <div class="py-2 flex flex-col">
                    <label for="" class="font-serif text-xl">TrainedLevel</label>
                     <div  class="w-full py-2 px-4 border-2 border-black">@Model.TrainedLevel</div>
                </div>
            </form>
        </div>
    </div>