dogAdoption/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using dogAdoption.Models;

namespace dogAdoption.Controllers;

public class ContactController : Controller
{
    public IActionResult Contact()
    {
        return View();
    }
}

dogAdoption/Controllers/DogsController.cs
using Microsoft.AspNetCore.Mvc;
using dogAdoption.Models;
using dogAdoption.Data;


namespace dogAdoption.Controllers;

public class DogsController : Controller
{
    private readonly AppDbContext _dbContext;
    public DogsController(AppDbContext dbContext)
    {
        _dbContext = dbContext;
    }

    public IActionResult DogsLists()
    {   
        IEnumerable<Dog> dogs =  _dbContext.dogs.ToList();
        IEnumerable<Dog> availableDogs = from dog in dogs
                                    where dog.adopted != true
                                    select dog;
        return View(availableDogs);
    }


    public async Task<IActionResult> DogDetails(int id)
    {
        var singleDog = await _dbContext.dogs.FindAsync(id);
        if (singleDog == null)
        {
            return NotFound();
        }
        return View(singleDog);
    }


    public IActionResult Search()
    {
        return View();
    }
}

dogAdoption/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - dogAdoption</title>
    <link rel="stylesheet" href="~/css/tailwind.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/dogAdoption.styles.css" asp-append-version="true" />
</head>
<body>

     <!-- nav -->
        <header class="">
            <div class="container mx-auto flex justify-around items-center py-5">
                <h1 class="logo">AdoptMe</h1>
                <ul class="flex items-center">
                    <li class="font-serif text-2xl mr-8">
                        <a asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="font-serif text-2xl mr-8">
                        <a asp-controller="Dogs" asp-action="DogsLists">Dogs</a>
                    </li>
                    <li class="font-serif text-2xl mr-8">
                        <a asp-controller="Contact" asp-action="Contact">Contact</a>
                    </li>
                    <li class="font-serif text-2xl">
                        <a asp-controller="Home" asp-action="About">About</a>
                    </li>
                </ul>
            </div>
        </header>

        <main>
            @RenderBody();
        </main>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>