dogAdoption/Models/Dog.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace dogAdoption.Models
{
    public class Dog 
    {

        [Key]
        public int Id{ get;set; }
        [Required(ErrorMessage = "name is required")]
        [MinLength(2)]
        [MaxLength(200)]
        public string? Name{ get;set; }
        [Required(ErrorMessage = "age is required")]
        public int Age{ get;set; }
        [Required(ErrorMessage = "color is required")]
        [MinLength(2)]
        [MaxLength(200)]
        public string? Color{get;set;}
        [Required(ErrorMessage = "eyes-color is required")]
        [MinLength(2)]
        [MaxLength(200)]
        public string? EyesColor{get;set;}
        [Required(ErrorMessage = "health-condition is required")]
        public string? HealthCondition{get;set;}
        [Required(ErrorMessage = "disability is required")]
        public bool? Disability{get;set;}
        [Required(ErrorMessage = "trained-level is required")]
        [MaxLength(200)]
        public string? TrainedLevel{get;set;}
        public bool? adopted { get;set; }
        public IEnumerable<AdoptionRequest>? adoptionRequests{get;set;}
    }
}

dogAdoption/Controllers/AdoptionRequestController.cs
using Microsoft.AspNetCore.Mvc;
using dogAdoption.Models;
using dogAdoption.Data;


namespace dogAdoption.Controllers;

public class AdoptionRequestController : Controller
{
    private readonly AppDbContext _databaseContext;
    public AdoptionRequestController(AppDbContext dbContext)
    {
        _databaseContext = dbContext;
    }


    public async Task<IActionResult> Adopt(int? id)
    {
        // asking  if the user is sure on adopting a dog
        var dog = await _databaseContext.dogs.FindAsync(id);
        if(dog == null){ return NotFound(); }
        return View();
    }


    [HttpPost]
    public async Task<ActionResult>  Adopt([FromForm] AdoptionRequest request)
    {
        if(ModelState.IsValid)
        {
            await _databaseContext.adoptionRequests.AddAsync(request);
            await _databaseContext.SaveChangesAsync();
            return RedirectToAction("DogsLists", "Dogs");
        }
        return View();
    }
}

dogAdoption/Controllers/DogsController.cs
using Microsoft.AspNetCore.Mvc;
using dogAdoption.Models;
using dogAdoption.Data;


namespace dogAdoption.Controllers;

public class DogsController : Controller
{
    private readonly AppDbContext _dbContext;
    public DogsController(AppDbContext dbContext)
    {
        _dbContext = dbContext;
    }

    public IActionResult DogsLists()
    {   
        IEnumerable<Dog> dogs =  _dbContext.dogs.ToList();
        IEnumerable<Dog> availableDogs = from dog in dogs
                                    where dog.adopted != true
                                    select dog;
        return View(availableDogs);
    }


    public async Task<IActionResult> DogDetails(int id)
    {
        var singleDog = await _dbContext.dogs.FindAsync(id);
        if (singleDog == null)
        {
            return NotFound();
        }
        return View(singleDog);
    }


    public IActionResult Search()
    {
        return View();
    }
}

dogAdoption/Views/Dogs/DogDetails.cshtml
 
 @model dogAdoption.Models.Dog;


 <div class="">
        <div class="container mx-auto max-w-3xl px-10 py-20">
            <h1 class="detailsheader pb-5">@Model.Name details..</h1>
            
            <div class="pb-5">
                <button class="font-serif text-white text-xl bg-green-600 py-3 px-10 shadow-xl">
                    <a asp-action="Adopt" asp-controller="AdoptionRequest" asp-route-id="@Model.Id">Adopt</a>
                </button>
            </div>
            
            <div class="grid grid-cols-2">
                <div class="">
                    <img src="/images/five.jpg" alt="" class="w-auto">
                </div>
                <div class="pl-5">
                    <p class="detailOne pb-2">Name: @Model.Name</p>
                    <p class="detailOne pb-2">Age: @Model.Age years</p>
                    <p class="detailOne pb-2">Eyes-Color: @Model.EyesColor</p>/
                    <p class="detailOne pb-2">Color: @Model.Color</p>
                    <p class="detailOne pb-2">Health: @Model.HealthCondition</p>
                    <p class="detailOne pb-2">Disability: @Model.Disability</p>
                    <p class="detailOne pb-2">TrainedLevel: @Model.TrainedLevel</p>
                </div>
            </div>
        </div>
    </div>

dogAdoption/Views/Dogs/DogsLists.cshtml
@model IEnumerable<dogAdoption.Models.Dog>;

<div class="">
        <div class="container mx-auto max-w-5xl px-10 py-20">
            <h1 class="dogsheader pb-8">Browse-our-lovely-Dogs</h1>
            <div class="max-w-xl flex pb-8">
                <input type="text" placeholder="eg eyes-color, skin-color, age" class="border-2 border-black py-1 px-4 text-xl shadow-xl w-full mr-4">
                <button class="bg-red-600 shadow-xl text-white font-bold py-3 text-xl px-10 ">Search</button>
            </div>
            <h2 class="font-serif text-2xl pb-20 tracking-wider font-bold">@Model.Count() Dogs available</h2>

            @if (@Model.Count() >= 1)
            {
                
            <div class="grid grid-cols-3 gap-8">
                
                @foreach (var dog in Model)
                {                   
                <div class=" cursor-pointer">
                    <img src="/images/five.jpg" alt="" class="w-full">
                    <div class="py-4 shadow-xl px-3">
                        <h2 class="dogHeader">@dog.Name</h2>
                        <p class="dogsecond">Age: @dog.Age yrs</p>
                        <a class="doglink">
                            <a asp-action="DogDetails" asp-controller="dogs" asp-route-id="@dog.Id">More_Info</a>
                        </a>
                    </div>
                </div>
                }

            </div>
            }

        </div>
    </div>