dogAdoption/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using dogAdoption.Models;
using System.Collections.Generic;

namespace dogAdoption.Controllers;

public class AdminController : Controller
{
    public IActionResult MainAdmin()
    {
        return View();
    }
}

dogAdoption/Controllers/AdoptionAdminController.cs
using Microsoft.AspNetCore.Mvc;
using dogAdoption.Models;
using dogAdoption.Data;
using Microsoft.EntityFrameworkCore;

namespace dogAdoption.Controllers;

public class AdoptionAdminController : Controller
{

    private readonly AppDbContext _databaseContext;
    public AdoptionAdminController(AppDbContext appDbContext)
    {
        _databaseContext = appDbContext;
    }

    public async Task<IActionResult> AdoptionRequestsAdmin() //displays pending
    {
        var requests = await _databaseContext.adoptionRequests.ToListAsync();
        IEnumerable<AdoptionRequest> pendingRequests = from request in requests
                            where request.Accepted != true && request.Accepted != false
                            select request;
        return View(pendingRequests);
    }


    [HttpGet]
    public async Task<IActionResult> requestDetail(int? id)
    {
        if(id == 0){ return NotFound(); }
        var request = await _databaseContext.adoptionRequests.FindAsync(id);
        if (request == null)
        {
            return NotFound();
        }
        return View(request);
    }


    public async Task<IActionResult> AdoptionAcceptedRequests()
    {
        var requests = await _databaseContext.adoptionRequests.ToListAsync();
        IEnumerable<AdoptionRequest> accepted = from request in requests
                            where request.Accepted == true
                            select request;
        return View(accepted);
    }


    public IActionResult AdoptionDeclinedRequests()
    {
        var requests = _databaseContext.adoptionRequests.ToList();
        IEnumerable<AdoptionRequest> declined = from request in requests
                            where request.Accepted == false
                            select request;
        return View(declined);
    }


    [HttpPost]
    public async Task<IActionResult> acceptAdoption(int id)
    {
        if(id ==0 ){ return NotFound(); }
        var request = await _databaseContext.adoptionRequests.FindAsync(id);
        if (request == null)
        {
            return NotFound();
        }
        request.Accepted = true;
        // inform the client via email

        // change the dog to adopted true

        var ids = request.dog?.Id;
        var getDogWithSameId = await _databaseContext.dogs.FindAsync(ids);
        if(getDogWithSameId == null){ return BadRequest(); }
        getDogWithSameId.adopted = true;
        // request.dog.adopted = true;
        await _databaseContext.SaveChangesAsync();
        return RedirectToAction(nameof(AdoptionAcceptedRequests));
    }


    [HttpPost]
    public async Task<IActionResult> declineAdoption(int id)
    {
        if (id ==0 ){ return BadRequest(); }
        var request = await _databaseContext.adoptionRequests.FindAsync(id);
        if (request == null)
        {
            return NotFound();
        }
        request.Accepted = false;
        // inform the client via email
        await _databaseContext.SaveChangesAsync();
        return RedirectToAction(nameof(AdoptionDeclinedRequests));
    }


}

dogAdoption/Views/AdoptionAdmin/AdoptionAcceptedRequests.cshtml
 @model IEnumerable<dogAdoption.Models.AdoptionRequest>;
 
 
 <div class="">
        <div class="container mx-auto max-w-6xl px-10 py-20">
            <h1 class="aboutheader pb-6">Admin-Panel-Adoptions</h1>

            <div class="pb-5">
                <h1 class="font-sans my-5 text-4xl bg-red-500 py-4 px-10">Adoption-Menu</h1>
            </div>
            <div class="pb-10">
                <button class="font-sans text-xl bg-red-600 py-3 px-10 text-white">Declined-lists</button>
                <button class="font-sans text-xl bg-black py-3 px-10 text-white">Pending-lists</button>
            </div>

            @if(@Model.Count() >= 1)
            {
                <h1 class="detailsheader pb-6">List of Accepted Adoption Requests</h1>

                <table class="table tablefont table-fixed w-full text-center ">
                    <thead class="bg-black text-white">
                        <tr>
                            <th class="py-2">Id</th>
                            <th>FirstName</th>
                            <th>LastName</th>
                            <th>Email</th>
                            <th>Dog</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var request in Model)
                        {
                        <tr class="border-b-2 text-xl font-serif text-gray-700 border-red-600">
                            <td class="py-4 ">@request.Id</td>
                            <th class="underline">@request.FirstName</th>
                            <th>@request.LastName</th>
                            <th>@request.Email</th>
                            <th>@request.dog?.Name</th>
                        </tr>   
                        }
                    </tbody>
                </table>
            }else
            {
                <h1>There's no accepted adoption requests</h1>
            }


        </div>
    </div>

dogAdoption/Views/AdoptionAdmin/AdoptionDeclinedRequests.cshtml
@model IEnumerable<dogAdoption.Models.AdoptionRequest>;

 <div class="">
        <div class="container mx-auto max-w-6xl px-10 py-20">
            <h1 class="aboutheader pb-6">Admin-Panel-Adoptions</h1>

            <div class="pb-5">
                <h1 class="font-sans my-5 text-4xl bg-red-500 py-4 px-10">Adoption-Menu</h1>
            </div>
            <div class="pb-10">
                <button class="font-sans text-xl bg-green-600 py-3 px-10 text-white">accepted-lists</button>
                <button class="font-sans text-xl bg-black py-3 px-10 text-white">Pending-lists</button>
            </div>

            @if(@Model.Count() >= 1)
            {
                <h1 class="detailsheader pb-6">List of Rejected Adoption Requests</h1>

                <table class="table tablefont table-fixed w-full text-center ">
                    <thead class="bg-black text-white">
                        <tr>
                            <th class="py-2">Id</th>
                            <th>FirstName</th>
                            <th>LastName</th>
                            <th>Email</th>
                            <th>Dog</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var request in Model)
                        {
                        <tr class="border-b-2 text-xl font-serif text-gray-700 border-red-600">
                            <td class="py-4 ">@request.Id</td>
                            <th class="underline">@request.FirstName</th>
                            <th>@request.LastName</th>
                            <th>@request.Email</th>
                            <th>@request.dog?.Name</th>
                        </tr>   
                        }
                    </tbody>
                </table>
            }else
            {
                <h1>There's no rejected adoption requests</h1>
            }

        </div>
    </div>

dogAdoption/Views/AdoptionAdmin/AdoptionRequestsAdmin.cshtml
@model IEnumerable<dogAdoption.Models.AdoptionRequest>;

 <div class="">
        <div class="container mx-auto max-w-6xl px-10 py-20">
              <h1 class="aboutheader pb-6">
                <a asp-action="MainAdmin" asp-controller="Admin">MainAdmin </a>
            </h1>


            <div class="pb-5">
                <h1 class="font-sans my-5 text-4xl bg-red-500 py-4 px-10">Adoption-Menu</h1>
            </div>
            <div class="pb-10">
                <button class="font-sans text-xl bg-green-600 py-3 px-10 text-white">
                    <a asp-action="AdoptionAcceptedRequests" asp-controller="AdoptionAdmin">List_Of_Accepted_Adoptions</a>
                </button>
                <button class="font-sans text-xl bg-red-600 py-3 px-10 text-white">
                    <a asp-action="AdoptionDeclinedRequests" asp-controller="AdoptionAdmin">List_Of_Rejected_Adoptions</a>
                </button>
            </div>

            @if (Model.Count() >= 1)
            {
                
            <h1 class="detailsheader pb-6">List of pending-applications</h1>

            <table class="table tablefont table-fixed w-full text-center ">
                <thead class="bg-black text-white">
                    <tr>
                        <th class="py-2">Id</th>
                        <th>FirstName</th>
                        <th>LastName</th>
                        <th>Email</th>
                        <th>Option1</th>
                        <th>Option2</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var request in Model)
                    {
                    <tr class="border-b-2 text-xl font-serif text-gray-700 border-red-600">
                        <td class="py-4 ">@request.Id</td>
                        <th class="underline">
                            <a asp-action="requestDetail" asp-controller="adoptionAdmin" asp-route-id="@request.Id">@request.FirstName</a>
                        </th>
                        <th>@request.LastName</th>
                        <th>@request.Email</th>
                        <th><button class="bg-green-700 text-white text-xl py-2 px-4">
                            <a asp-action="acceptAdoption" asp-controller=" AdoptionAdmin" asp-route-id="@request.Id">Accept</a>
                        </button></th>
                        <th><button class="bg-red-700 text-white text-xl py-2 px-4">
                            <a asp-action="declineAdoption" asp-controller=" AdoptionAdmin" asp-route-id="@request.Id">Reject</a>
                        </button></th>
                    </tr>
                    }

                </tbody>
            </table>
            } 
            else
            {
                <h1>The pending request lists is empty</h1>
            }

        </div>
    </div>

dogAdoption/Views/AdoptionAdmin/requestDetail.cshtml
@model dogAdoption.Models.AdoptionRequest;

    <div class="">
        <div class="container mx-auto max-w-3xl px-10 py-20">
            <h1 class="detailsheader pb-4">Application-Details</h1>
            <div class="pb-6">
                <button class="font-sans text-xl bg-red-400 py-3 px-10 text-white">Application-Lists</button>
            </div>

            <form>
                <div class="py-2 flex flex-col">
                    <label asp-for="FirstName" class="font-serif text-xl"></label>
                    <p class="w-full py-2 px-4 border-2 border-black">@Model.FirstName</p>
                </div>
                <div class="py-2 flex flex-col">
                    <label asp-for="LastName" class="font-serif text-xl"></label>
                    <p class="w-full py-2 px-4 border-2 border-black">@Model.LastName</p>
                </div>
                <div class="py-2 flex flex-col">
                    <label asp-for="Adress" class="font-serif text-xl"></label>
                    <p class="w-full py-2 px-4 border-2 border-black">@Model.Adress</p>
                </div>
                <div class="py-2 flex flex-col">
                    <label asp-for="Email" class="font-serif text-xl"></label>
                    <p class="w-full py-2 px-4 border-2 border-black">@Model.Email</p>
                </div>
            </form>
        </div>
    </div>